// ============================================================================
// ISiK Vitalparameter Bundle
// ============================================================================

Instance: mii-exa-test-data-bundle-isik-vitalparameter-1
InstanceOf: Bundle
Usage: #example
Description: "Bundle: ISiK 6.0.0 Observation-Testdaten - Vitalparameter (10 Profile), LebensZustand-Familie, Laboruntersuchungs-Familie, MII-ICU-Monitoring- und Koerpertemperatur-Familie (sd-mii-icu-*)"
* insert TestDataLabel
* meta.source = "https://www.charite.de/fhir/kds-testdata"
* type = #transaction
* timestamp = "2026-05-14T12:00:00+02:00"
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-patient-1, Patient)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-encounter-1, Encounter)
// Observations (ISiK 6.0.0 Vitalparameter)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-atemfrequenz-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-herzfrequenz-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-blutdruck-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-sauerstoffsaettigung-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-koerpergewicht-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-koerpergroesse-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-koerperkerntemperatur-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-kopfumfang-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-gcs-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-ekg-1, Observation)
// LebensZustand-Familie (ISiKRaucherStatus: via modul-kardiologie abgedeckt)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-alkoholabusus-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-schwangerschaft-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-entbindungstermin-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-stillstatus-1, Observation)
// Laboruntersuchungs-Familie
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-generisch-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-crp-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-gfr-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-hb-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-pct-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-kreatinin-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-natrium-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-tsh-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-thrombozyten-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-labor-troponin-1, Observation)
// MII-ICU-Monitoring-Familie (sd-mii-icu-*)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-muv-generisch-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-puls-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-hzv-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-ideales-gewicht-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-icp-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-gewicht-percentil-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-groesse-percentil-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-lv-herzindex-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-lv-schlagvolumen-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-lv-svi-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-lv-hi-ind-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-lv-sv-ind-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-lv-svi-ind-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-lv-hzv-ind-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-o2sat-art-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-o2sat-praeduktal-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-o2sat-postduktal-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-wedge-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-pvri-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-svri-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-zvd-1, Observation)
// Pulsatile Druecke (Komponenten Sys/Dia/Mean)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-pulsatil-generisch-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-lap-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-lvp-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-rap-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-rvp-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-pap-1, Observation)
// Koerpertemperatur-Familie (alle Messorte)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-generisch-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-atemwege-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-brust-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-bws-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-gelenk-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-hws-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-lws-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-myokard-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-nasal-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-nasopharynx-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-stirn-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-kern-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-rektal-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-blut-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-achsel-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-harnblase-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-leiste-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-oesophagus-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-trommelfell-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-sublingual-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-temp-vaginal-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-isik-vitalparameter-kerntemp-stirn-1, Observation)
