Instance: mii-exa-pro-dass-dass21-response-01
InstanceOf: https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/StructureDefinition/mii-pr-pro-questionnaire-response
Usage: #example
* subject = Reference(mii-exa-pro-patient)
* item[0].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q01"
* item[=].text = "I found it hard to wind down"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich fand es schwer abzuschalten"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q02"
* item[=].text = "I was aware of dryness of my mouth"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich bemerkte Mundtrockenheit"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q03"
* item[=].text = "I couldn't seem to experience any positive feeling at all"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich konnte überhaupt keine positiven Gefühle mehr erleben"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q04"
* item[=].text = "I experienced breathing difficulty"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich hatte Atemschwierigkeiten"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q05"
* item[=].text = "I found it difficult to work up the initiative to do things"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich fand es schwierig, die Initiative zum Tun aufzubringen"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q06"
* item[=].text = "I tended to over-react to situations"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich neigte dazu, auf Situationen überzureagieren"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf gar nicht auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q07"
* item[=].text = "I experienced trembling (e.g., in the hands)"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich zitterte (z.B. an den Händen)"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q08"
* item[=].text = "I felt that I was using a lot of nervous energy"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich merkte, dass ich viel nervöse Energie verbrauchte"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q09"
* item[=].text = "I was worried about situations in which I might panic and make a fool of myself"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich machte mir Sorgen über Situationen, in denen ich in Panik geraten könnte"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q10"
* item[=].text = "I felt that I had nothing to look forward to"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich hatte das Gefühl, dass ich nichts erwarten konnte"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q11"
* item[=].text = "I found myself getting agitated"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich merkte, dass ich unruhig wurde"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q12"
* item[=].text = "I found it difficult to relax"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich fand es schwierig, mich zu entspannen"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q13"
* item[=].text = "I felt down-hearted and blue"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich fühlte mich niedergeschlagen und traurig"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q14"
* item[=].text = "I was intolerant of anything that kept me from getting on with what I was doing"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich war ungeduldig, wenn ich aufgehalten wurde"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q15"
* item[=].text = "I felt I was close to panic"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich fühlte mich einer Panik nahe"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q16"
* item[=].text = "I was unable to become enthusiastic about anything"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich konnte mich für nichts begeistern"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-2 "Applied to me to a considerable degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf in beträchtlichem Maße auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q17"
* item[=].text = "I felt I wasn't worth much as a person"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich hatte das Gefühl, nicht viel wert zu sein"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q18"
* item[=].text = "I felt that I was rather touchy"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich merkte, dass ich ziemlich empfindlich war"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-0 "Did not apply to me at all"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf gar nicht auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q19"
* item[=].text = "I was aware of the action of my heart in the absence of physical exertion"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich nahm meinen Herzschlag wahr, ohne körperlich aktiv zu sein"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q20"
* item[=].text = "I felt scared without any good reason"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich fürchtete mich ohne ersichtlichen Grund"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-dass-21#dass-dass21-answer-1 "Applied to me to some degree"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "Traf bis zu einem gewissen Grad auf mich zu"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "dass-dass21-q21"
* item[=].text = "I felt that life was meaningless"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ich fand das Leben sinnlos"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueDecimal = 12
* item[=].linkId = "dass-dass21-score-raw-depression"
* item[=].text = "DASS-21 Depression Raw Score"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "DASS-21 Depression Rohwert"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueDecimal = 5
* item[=].linkId = "dass-dass21-score-raw-anxiety"
* item[=].text = "DASS-21 Anxiety Raw Score"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "DASS-21 Angst Rohwert"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueDecimal = 11
* item[=].linkId = "dass-dass21-score-raw-stress"
* item[=].text = "DASS-21 Stress Raw Score"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "DASS-21 Stress Rohwert"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueDecimal = 24
* item[=].linkId = "dass-dass21-score-equiv-depression"
* item[=].text = "DASS-21 Depression Score (DASS-42 equivalent)"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "DASS-21 Depression Score (DASS-42 Äquivalent)"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueDecimal = 10
* item[=].linkId = "dass-dass21-score-equiv-anxiety"
* item[=].text = "DASS-21 Anxiety Score (DASS-42 equivalent)"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "DASS-21 Angst Score (DASS-42 Äquivalent)"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueDecimal = 22
* item[=].linkId = "dass-dass21-score-equiv-stress"
* item[=].text = "DASS-21 Stress Score (DASS-42 equivalent)"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "DASS-21 Stress Score (DASS-42 Äquivalent)"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* language = #en
* questionnaire = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Questionnaire/mii-qst-pro-dass-dass21|2027.0.0-ballot.1"
* status = #completed
* authored = "2026-02-01"