Instance: mii-exa-pro-whodas12-response-01
InstanceOf: https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/StructureDefinition/mii-pr-pro-questionnaire-response
Usage: #example
* subject = Reference(mii-exa-pro-patient)
* item[0].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q01"
* item[=].text = "Standing for long periods such as 30 minutes?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "längere Zeit (ca. 30 min) zu stehen?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q02"
* item[=].text = "Taking care of your household responsibilities?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ihren Haushaltspflichten nachzukommen?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q03"
* item[=].text = "Learning a new task, for example, learning how to get to a new place?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Neue Aufgaben zu lernen (z.B. erlernen an einen neuen Ort zu gelangen, den sie nicht kannten?)"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q04"
* item[=].text = "Joining in community activities (for example, festivities, religious or other activities) in the same way as anyone else can?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Wie viele Schwierigkeiten hatten Sie, an gesellschaftlichen Aktivitäten (wie z.B. Festlichkeiten, religiöse oder andere Aktivitäten) in der gleichen Art und Weise teilzunehmen, wie jeder andere?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q05"
* item[=].text = "How much have you been emotionally affected by your health problems?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Wie sehr wurden Sie durch Ihren gesundheitlichen Zustand emotional belastet?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q06"
* item[=].text = "Concentrating on doing something for ten minutes?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Sich auf etwas für 10 Minuten zu konzentrieren?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q07"
* item[=].text = "Walking a long distance such as a kilometre?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Eine längere Strecke (ca. einen Kilometer) zu Fuß zu gehen?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q08"
* item[=].text = "Washing your whole body?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Ihren gesamten Körper zu waschen?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q09"
* item[=].text = "Getting dressed?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "sich anzuziehen?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q10"
* item[=].text = "Dealing with people you do not know?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Im Umgang mit anderen Personen, die Sie nicht kennen?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q11"
* item[=].text = "Maintaining a friendship?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Eine Freundschaft aufrechtzuerhalten?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-whodas-12#whodas12-answer-2 "Moderate"
* item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].answer.valueCoding.display.extension.extension[=].valueString = "mäßige"
* item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "whodas-whodas12-q12"
* item[=].text = "Your day-to-day work/school?"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "Bei der Bewältigung des Arbeits-/Schulalltags?"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].answer.valueDecimal = 24
* item[=].linkId = "whodas-whodas12-score-simple-sum"
* item[=].text = "WHODAS 2.0 12-Item simple sum score (0-48)"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "WHODAS 2.0 12-Item Summenwert (Simple Sum, 0-48)"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* questionnaire = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Questionnaire/mii-qst-pro-whodas-whodas12|2027.0.0-ballot.1"
* status = #completed
* language = #en
* authored = "2026-02-01"