Instance: mii-exa-pro-bdi-bdi2
InstanceOf: https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/StructureDefinition/mii-pr-pro-questionnaire-response
Usage: #example
* subject = Reference(mii-exa-pro-patient)
* item[0].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q01"
* item[=].text = "[TEST PLACEHOLDER: Question 1 about mood - NOT actual BDI-II text]"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q02"
* item[=].text = "[TEST PLACEHOLDER: Question 2 about outlook - NOT actual BDI-II text]"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-0 "0 points"
* item[=].linkId = "bdi-bdi2-q03"
* item[=].text = "[TEST PLACEHOLDER: Question 3 about experiences - NOT actual BDI-II text]"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-2 "2 points"
* item[=].linkId = "bdi-bdi2-q04"
* item[=].text = "[TEST PLACEHOLDER: Question 4 about enjoyment - NOT actual BDI-II text]"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q05"
* item[=].text = "[TEST PLACEHOLDER: Question 5 about feelings - NOT actual BDI-II text]"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-0 "0 points"
* item[=].linkId = "bdi-bdi2-q06"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q07"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q08"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-0 "0 points"
* item[=].linkId = "bdi-bdi2-q09"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q10"
* item[=].text = "[TEST PLACEHOLDER: Question 10 about emotions - NOT actual BDI-II text]"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-0 "0 points"
* item[=].linkId = "bdi-bdi2-q11"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-2 "2 points"
* item[=].linkId = "bdi-bdi2-q12"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q13"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q14"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-2a "2 points (variant a)"
* item[=].linkId = "bdi-bdi2-q15"
* item[=].text = "[TEST PLACEHOLDER: Question 15 about energy (uses extended scale) - NOT actual BDI-II text]"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q16"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1a "1 point (variant a)"
* item[=].linkId = "bdi-bdi2-q17"
* item[=].text = "[TEST PLACEHOLDER: Question 17 about appetite (uses extended scale) - NOT actual BDI-II text]"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-2 "2 points"
* item[=].linkId = "bdi-bdi2-q18"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-1 "1 point"
* item[=].linkId = "bdi-bdi2-q19"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-0 "0 points"
* item[=].linkId = "bdi-bdi2-q20"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-bdi-bdi2#bdi-bdi2-answer-0 "0 points"
* item[=].linkId = "bdi-bdi2-q21"
* item[=].text = "[TEST PLACEHOLDER: Question 21 about interests - NOT actual BDI-II text]"
* item[+].answer.valueDecimal = 19
* item[=].linkId = "bdi-bdi2-score-total"
* item[=].text = "BDI-II Gesamtscore (0-63)"
* language = #de
* questionnaire = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Questionnaire/mii-qst-pro-bdi-bdi2|2027.0.0-ballot.1"
* status = #completed
* authored = "2023-10-01T12:00:00Z"