Instance: mii-exa-pro-eortc-qlq-c30-bundle
InstanceOf: Bundle
Usage: #example
* entry[0].request.method = #PUT
* entry[=].request.url = "Questionnaire/mii-qst-pro-eortc-qlq-c30"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Questionnaire/mii-qst-pro-eortc-qlq-c30"
* entry[=].resource = mii-qst-pro-eortc-qlq-c30
* entry[+].request.method = #PUT
* entry[=].request.url = "QuestionnaireResponse/mii-exa-pro-eortc-qlq-c30-response"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/QuestionnaireResponse/mii-exa-pro-eortc-qlq-c30-response"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-response
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-pf"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-pf"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-pf
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-rf"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-rf"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-rf
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-ef"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-ef"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-ef
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-cf"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-cf"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-cf
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-sf"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-sf"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-sf
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-fa"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-fa"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-fa
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-nv"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-nv"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-nv
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-pa"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-pa"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-pa
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-dy"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-dy"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-dy
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-sl"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-sl"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-sl
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-ap"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-ap"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-ap
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-co"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-co"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-co
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-di"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-di"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-di
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-fi"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-fi"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-fi
* entry[+].request.method = #PUT
* entry[=].request.url = "Observation/mii-exa-pro-eortc-qlq-c30-observation-ql"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Observation/mii-exa-pro-eortc-qlq-c30-observation-ql"
* entry[=].resource = mii-exa-pro-eortc-qlq-c30-observation-ql
* entry[+].resource = Inline-Instance-for-mii-exa-pro-eortc-qlq-c30-bundle-17
* entry[=].request.method = #PUT
* entry[=].request.url = "Patient/mii-exa-pro-patient"
* entry[=].fullUrl = "http://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Patient/mii-exa-pro-patient"
* type = #transaction