Instance: mii-exa-pro-promis-29-response
InstanceOf: https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/StructureDefinition/mii-pr-pro-questionnaire-response
Usage: #example
* item[0].item[0].linkId = "PROMIS-29.PhysicalFunction.Description"
* item[=].item[=].text = "Sind Sie zu folgenden Tätigkeiten imstande:"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Sind Sie zu folgenden Tätigkeiten imstande:"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13920-6 "With some difficulty"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mit einigen Schwierigkeiten"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-pfa11"
* item[=].item[=].text = "Are you able to do chores such as vacuuming or yard work [PROMIS]"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Können Sie Hausarbeiten erledigen, z.B. Staubsaugen oder Gartenarbeit?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13920-6 "With some difficulty"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mit einigen Schwierigkeiten"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-pfa21"
* item[=].item[=].text = "Are you able to go up and down stairs at a normal pace [PROMIS]"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Können Sie mit normaler Geschwindigkeit Treppen hoch- und runtergehen?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13918-0 "With a little difficulty"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mit geringen Schwierigkeiten"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-pfa23"
* item[=].item[=].text = "Are you able to go for a walk of at least 15 minutes [PROMIS]"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Können Sie mindestens 15 Minuten lang spazieren gehen?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13920-6 "With some difficulty"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mit einigen Schwierigkeiten"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-pfa53"
* item[=].item[=].text = "Are you able to run errands and shop [PROMIS]"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Können Sie Besorgungen machen und einkaufen gehen?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "PROMIS-29.PhysicalFunction"
* item[=].text = "KÖRPERLICHE FUNKTION"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "KÖRPERLICHE FUNKTION"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].item[0].linkId = "PROMIS-29.Anxiety.Description"
* item[=].item[=].text = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10066-1 "Rarely"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Selten"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-edanx01"
* item[=].item[=].text = "Ich fürchtete mich."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich fürchtete mich."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10082-8 "Sometimes"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Manchmal"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-edanx40"
* item[=].item[=].text = "Ich fand es schwer, auf etwas anderes zu achten als auf meine Angst."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich fand es schwer, auf etwas anderes zu achten als auf meine Angst."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10066-1 "Rarely"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Selten"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-edanx41"
* item[=].item[=].text = "Meine Sorgen haben mich überwältigt."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Meine Sorgen haben mich überwältigt."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10066-1 "Rarely"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Selten"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-edanx53"
* item[=].item[=].text = "Ich fühlte mich unruhig."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich fühlte mich unruhig."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "PROMIS-29.Anxiety"
* item[=].text = "ANGST"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "ANGST"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].item[0].linkId = "PROMIS-29.Depression.Description"
* item[=].item[=].text = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10082-8 "Sometimes"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Manchmal"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-eddep04"
* item[=].item[=].text = "Ich fühlte mich wertlos."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich fühlte mich wertlos."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10082-8 "Sometimes"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Manchmal"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-eddep06"
* item[=].item[=].text = "Ich fühlte mich hilflos."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich fühlte mich hilflos."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10044-8 "Often"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Oft"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-eddep29"
* item[=].item[=].text = "Ich fühlte mich niedergeschlagen."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich fühlte mich niedergeschlagen."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10082-8 "Sometimes"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Manchmal"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-eddep41"
* item[=].item[=].text = "Ich fühlte mich hoffnungslos."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich fühlte mich hoffnungslos."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "PROMIS-29.Depression"
* item[=].text = "DEPRESSION"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "DEPRESSION"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].item[0].linkId = "PROMIS-29.Fatigue.Description"
* item[=].item[=].text = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13902-4 "Quite a bit"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Ziemlich"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-hi7"
* item[=].item[=].text = "Ich bin erschöpft."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich bin erschöpft."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13902-4 "Quite a bit"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Ziemlich"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-an3"
* item[=].item[=].text = "Es fällt mir schwer, etwas anzufangen, weil ich müde bin."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Es fällt mir schwer, etwas anzufangen, weil ich müde bin."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13909-9 "Somewhat"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mäßig"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-fatexp41"
* item[=].item[=].text = "Wie ausgelaugt fühlten Sie sich im Allgemeinen?"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Wie ausgelaugt fühlten Sie sich im Allgemeinen?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13902-4 "Quite a bit"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Ziemlich"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-fatexp40"
* item[=].item[=].text = "Wie erschöpft waren Sie im Allgemeinen?"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Wie erschöpft waren Sie im Allgemeinen?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "PROMIS-29.Fatigue"
* item[=].text = "ERSCHÖPFUNG"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "ERSCHÖPFUNG"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].item[0].linkId = "PROMIS-29.Sleep.Description"
* item[=].item[=].text = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA8968-5 "Fair"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mäßig"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-sleep109"
* item[=].item[=].text = "Meine Schlafqualität war ..."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Meine Schlafqualität war ..."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13909-9 "Somewhat"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mäßig"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-sleep116"
* item[=].item[=].text = "Mein Schlaf war erfrischend."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Mein Schlaf war erfrischend."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13909-9 "Somewhat"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mäßig"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-sleep20"
* item[=].item[=].text = "Ich hatte Schlafprobleme."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich hatte Schlafprobleme."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13863-8 "A little bit"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Ein wenig"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-sleep44"
* item[=].item[=].text = "Ich hatte Schwierigkeiten einzuschlafen."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Ich hatte Schwierigkeiten einzuschlafen."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "PROMIS-29.Sleep"
* item[=].text = "SCHLAFSTÖRUNGEN"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "SCHLAFSTÖRUNGEN"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].item[0].linkId = "PROMIS-29.Social.Description"
* item[=].item[=].text = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "In den letzten 7 Tagen:"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10082-8 "Sometimes"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Manchmal"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-srpper23-caps"
* item[=].item[=].text = "Es fällt mir schwer, meine gewohnte Arbeit zu erledigen (einschließlich der Arbeit zu Hause)."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Es fällt mir schwer, meine gewohnte Arbeit zu erledigen (einschließlich der Arbeit zu Hause)."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10082-8 "Sometimes"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Manchmal"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-srpper11-caps"
* item[=].item[=].text = "Es fällt mir schwer, allen meinen regelmäßigen Freizeitaktivitäten mit anderen nachzugehen."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Es fällt mir schwer, allen meinen regelmäßigen Freizeitaktivitäten mit anderen nachzugehen."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10066-1 "Rarely"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Selten"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-srpper18-caps"
* item[=].item[=].text = "Es fällt mir schwer, allen Aktivitäten nachzugehen, die ich mit meiner Familie machen möchte."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Es fällt mir schwer, allen Aktivitäten nachzugehen, die ich mit meiner Familie machen möchte."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA10082-8 "Sometimes"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Manchmal"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-srpper46-caps"
* item[=].item[=].text = "Es fällt mir schwer, allen Aktivitäten nachzugehen, die ich mit Freunden machen möchte."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Es fällt mir schwer, allen Aktivitäten nachzugehen, die ich mit Freunden machen möchte."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "PROMIS-29.Social"
* item[=].text = "SOZIALE TEILHABE"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "SOZIALE TEILHABE"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].item[0].linkId = "PROMIS-29.PainInterference.Description"
* item[=].item[=].text = "In den letzten 7 Tagen: Inwieweit beeinträchtigten Schmerzen..."
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "In den letzten 7 Tagen: Inwieweit beeinträchtigten Schmerzen..."
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13909-9 "Somewhat"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mäßig"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-painin9"
* item[=].item[=].text = "Wie sehr beeinträchtigten Schmerzen Ihre Alltagsaktivitäten?"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Wie sehr beeinträchtigten Schmerzen Ihre Alltagsaktivitäten?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13909-9 "Somewhat"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mäßig"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-painin22"
* item[=].item[=].text = "Wie sehr beeinträchtigten Schmerzen Ihre häuslichen Tätigkeiten?"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Wie sehr beeinträchtigten Schmerzen Ihre häuslichen Tätigkeiten?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13863-8 "A little bit"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Ein wenig"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-painin31"
* item[=].item[=].text = "Wie sehr beeinträchtigten Schmerzen Ihre Fähigkeit, an sozialen Aktivitäten teilzunehmen?"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Wie sehr beeinträchtigten Schmerzen Ihre Fähigkeit, an sozialen Aktivitäten teilzunehmen?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueCoding = http://loinc.org#LA13909-9 "Somewhat"
* item[=].item[=].answer.valueCoding.display.extension.extension[0].url = "lang"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueCode = #de
* item[=].item[=].answer.valueCoding.display.extension.extension[+].url = "content"
* item[=].item[=].answer.valueCoding.display.extension.extension[=].valueString = "Mäßig"
* item[=].item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[=].linkId = "promis-painin34"
* item[=].item[=].text = "Wie sehr beeinträchtigten Schmerzen Sie bei Ihrer Hausarbeit?"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "Wie sehr beeinträchtigten Schmerzen Sie bei Ihrer Hausarbeit?"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "PROMIS-29.PainInterference"
* item[=].text = "SCHMERZBEDINGTE BEEINTRÄCHTIGUNG"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "SCHMERZBEDINGTE BEEINTRÄCHTIGUNG"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].item.answer.valueInteger = 5
* item[=].item.linkId = "promis-global07"
* item[=].item.text = "Wie würden Sie Ihre Schmerzen im Allgemeinen einschätzen?"
* item[=].item.text.extension.extension[0].url = "lang"
* item[=].item.text.extension.extension[=].valueCode = #de
* item[=].item.text.extension.extension[+].url = "content"
* item[=].item.text.extension.extension[=].valueString = "Wie würden Sie Ihre Schmerzen im Allgemeinen einschätzen?"
* item[=].item.text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "PROMIS-29.PainIntensity"
* item[=].text = "SCHMERZINTENSITÄT"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "SCHMERZINTENSITÄT"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[+].item[0].answer.valueDecimal = 13
* item[=].item[=].linkId = "promis-29-physical-function-raw"
* item[=].item[=].text = "PROMIS-29 Körperliche Funktion - Rohwert"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Körperliche Funktion - Rohwert"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 42.6
* item[=].item[=].linkId = "promis-29-physical-function-tscore"
* item[=].item[=].text = "PROMIS-29 Körperliche Funktion - T-Score"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Körperliche Funktion - T-Score"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 9
* item[=].item[=].linkId = "promis-29-anxiety-raw"
* item[=].item[=].text = "PROMIS-29 Angst - Rohwert"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Angst - Rohwert"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 56.8
* item[=].item[=].linkId = "promis-29-anxiety-tscore"
* item[=].item[=].text = "PROMIS-29 Angst - T-Score"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Angst - T-Score"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 13
* item[=].item[=].linkId = "promis-29-depression-raw"
* item[=].item[=].text = "PROMIS-29 Depression - Rohwert"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Depression - Rohwert"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 63.9
* item[=].item[=].linkId = "promis-29-depression-tscore"
* item[=].item[=].text = "PROMIS-29 Depression - T-Score"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Depression - T-Score"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 15
* item[=].item[=].linkId = "promis-29-fatigue-raw"
* item[=].item[=].text = "PROMIS-29 Erschöpfung - Rohwert"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Erschöpfung - Rohwert"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 64.9
* item[=].item[=].linkId = "promis-29-fatigue-tscore"
* item[=].item[=].text = "PROMIS-29 Erschöpfung - T-Score"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Erschöpfung - T-Score"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 11
* item[=].item[=].linkId = "promis-29-sleep-raw"
* item[=].item[=].text = "PROMIS-29 Schlafstörungen - Rohwert"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Schlafstörungen - Rohwert"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 53.6
* item[=].item[=].linkId = "promis-29-sleep-tscore"
* item[=].item[=].text = "PROMIS-29 Schlafstörungen - T-Score"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Schlafstörungen - T-Score"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 11
* item[=].item[=].linkId = "promis-29-social-raw"
* item[=].item[=].text = "PROMIS-29 Soziale Teilhabe - Rohwert"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Soziale Teilhabe - Rohwert"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 39.7
* item[=].item[=].linkId = "promis-29-social-tscore"
* item[=].item[=].text = "PROMIS-29 Soziale Teilhabe - T-Score"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Soziale Teilhabe - T-Score"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 11
* item[=].item[=].linkId = "promis-29-pain-interference-raw"
* item[=].item[=].text = "PROMIS-29 Schmerzbedingte Beeinträchtigung - Rohwert"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Schmerzbedingte Beeinträchtigung - Rohwert"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].item[+].answer.valueDecimal = 60.9
* item[=].item[=].linkId = "promis-29-pain-interference-tscore"
* item[=].item[=].text = "PROMIS-29 Schmerzbedingte Beeinträchtigung - T-Score"
* item[=].item[=].text.extension.extension[0].url = "lang"
* item[=].item[=].text.extension.extension[=].valueCode = #de
* item[=].item[=].text.extension.extension[+].url = "content"
* item[=].item[=].text.extension.extension[=].valueString = "PROMIS-29 Schmerzbedingte Beeinträchtigung - T-Score"
* item[=].item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[=].linkId = "PROMIS-29.Scores"
* item[=].text = "BEREICHS-BEWERTUNGEN"
* item[=].text.extension.extension[0].url = "lang"
* item[=].text.extension.extension[=].valueCode = #de
* item[=].text.extension.extension[+].url = "content"
* item[=].text.extension.extension[=].valueString = "BEREICHS-BEWERTUNGEN"
* item[=].text.extension.url = "http://hl7.org/fhir/StructureDefinition/translation"
* language = #en
* questionnaire = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Questionnaire/mii-qst-pro-promis-29|2027.0.0-ballot.1"
* status = #completed
* subject = Reference(mii-exa-pro-patient)
* authored = "2025-01-30T14:30:00Z"