Instance: mii-exa-pro-ssd-12-response
InstanceOf: https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/StructureDefinition/mii-pr-pro-questionnaire-response
Usage: #example
* item[0].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q01"
* item[=].text = "Ich denke, dass meine körperlichen Beschwerden Anzeichen einer ernsthaften Erkrankung sind."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q02"
* item[=].text = "Ich mache mir große Sorgen um meine Gesundheit."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q03"
* item[=].text = "Meine gesundheitlichen Sorgen behindern mich im Alltag."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q04"
* item[=].text = "Ich bin von der Ernsthaftigkeit meiner körperlichen Beschwerden überzeugt."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q05"
* item[=].text = "Meine körperlichen Beschwerden machen mir Angst."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q06"
* item[=].text = "Meine körperlichen Beschwerden beschäftigen mich den größten Teil des Tages."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q07"
* item[=].text = "Andere sagen mir, dass meine körperlichen Beschwerden nicht schlimm sind."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q08"
* item[=].text = "Ich mache mir Sorgen, dass meine körperlichen Beschwerden niemals aufhören werden."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q09"
* item[=].text = "Die Sorgen um meine Gesundheit rauben mir Energie."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q10"
* item[=].text = "Ich denke, dass die Ärzte meine körperlichen Beschwerden nicht ernst nehmen."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q11"
* item[=].text = "Ich mache mir Sorgen auch in Zukunft durch meine körperlichen Beschwerden beeinträchtigt zu bleiben."
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-ssd-12-answers#sometimes "manchmal"
* item[=].linkId = "ssd12-q12"
* item[=].text = "Durch meine körperlichen Beschwerden kann ich mich schlecht auf andere Dinge konzentrieren."
* item[+].answer.valueDecimal = 24
* item[=].linkId = "ssd12-score-total"
* item[=].text = "SSD-12 Summenwert (0-48)"
* status = #completed
* language = #de
* subject = Reference(mii-exa-pro-patient)
* authored = "2026-08-31T09:30:00Z"
* questionnaire = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Questionnaire/mii-qst-pro-ssd-12|2027.0.0-ballot.1"