Instance: mii-exa-pro-midos2-response-01
InstanceOf: https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/StructureDefinition/mii-pr-pro-questionnaire-response
Usage: #example
* subject = Reference(mii-exa-pro-patient)
* item[0].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-2 "mittlere"
* item[=].linkId = "midos2-q01-schmerz"
* item[=].text = "Schmerz"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-1 "leichte"
* item[=].linkId = "midos2-q02-uebelkeit"
* item[=].text = "Übelkeit"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-0 "keine"
* item[=].linkId = "midos2-q03-erbrechen"
* item[=].text = "Erbrechen"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-1 "leichte"
* item[=].linkId = "midos2-q04-luftnot"
* item[=].text = "Luftnot"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-2 "mittlere"
* item[=].linkId = "midos2-q05-verstopfung"
* item[=].text = "Verstopfung"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-3 "starke"
* item[=].linkId = "midos2-q06-schwaeche"
* item[=].text = "Schwäche"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-3 "starke"
* item[=].linkId = "midos2-q07-muedigkeit"
* item[=].text = "Müdigkeit"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-3 "starke"
* item[=].linkId = "midos2-q08-appetitmangel"
* item[=].text = "Appetitmangel"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-2 "mittlere"
* item[=].linkId = "midos2-q09-depressivitaet"
* item[=].text = "Depressivität"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-1 "leichte"
* item[=].linkId = "midos2-q10-angst"
* item[=].text = "Angst"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-severity-1 "leichte"
* item[=].linkId = "midos2-q11-anspannung"
* item[=].text = "Anspannung"
* item[+].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/CodeSystem/mii-cs-pro-midos2#midos2-wellbeing-2 "eher schlecht"
* item[=].linkId = "midos2-q12-wohlbefinden"
* item[=].text = "Wie würden Sie Ihr Wohlbefinden insgesamt einschätzen?"
* item[+].answer.valueString = "Schlafstörungen, häufiges nächtliches Erwachen"
* item[=].linkId = "midos2-q13-sonstiges"
* item[=].text = "Andere Beschwerden (bitte angeben)"
* language = #de
* questionnaire = "https://www.medizininformatik-initiative.de/fhir/ext/modul-pro/Questionnaire/mii-qst-pro-midos-midos2|2027.0.0-ballot.1"
* status = #completed
* authored = "2026-06-01"