version: '3.7'
services:
  synthea:
    build: .
    environment:
      N_PATIENTS: ${SYNTHEA_N_PATIENTS:-10}
    volumes:
      - "./generated-testdata:/gen/output"
      - "./synthea.properties:/gen/synthea.properties"
      - "./docker-entrypoint.sh:/gen/docker-entrypoint.sh"
