Instance: mii-exa-kardio-questionnaireresponse-arzt
InstanceOf: QuestionnaireResponse
Usage: #example
* contained = Beispielpatient
* item[0].item[0].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-kardio/CodeSystem/mii-cs-kardio-acribis-questionnaire-answer#respondent_physician "Arzt/Ärztin"
* item[=].item[=].linkId = "o_1"
* item[=].item[=].text = "Wer füllt den Fragebogen aus?"
* item[=].item[+].answer.item[0].item[0].answer.item[0].answer.valueDateTime = "2025-12-02T10:32:27.407Z"
* item[=].item[=].answer.item[=].item[=].answer.item[=].linkId = "551754048694"
* item[=].item[=].answer.item[=].item[=].answer.item[=].text = "ggf. Telefonat 1. Versuch (Tag 14 bis 21)"
* item[=].item[=].answer.item[=].item[=].answer.item[+].answer.valueDateTime = "2025-12-02T13:32:30.870Z"
* item[=].item[=].answer.item[=].item[=].answer.item[=].linkId = "339142957184"
* item[=].item[=].answer.item[=].item[=].answer.item[=].text = "ggf. Telefonat 2. Versuch (Tag 14 bis 21)"
* item[=].item[=].answer.item[=].item[=].answer.item[+].answer.valueDateTime = "2025-12-02T15:32:33.485Z"
* item[=].item[=].answer.item[=].item[=].answer.item[=].linkId = "336352021151"
* item[=].item[=].answer.item[=].item[=].answer.item[=].text = "ggf. Telefonat 3. Versuch (Tag 14 bis 21)"
* item[=].item[=].answer.item[=].item[=].answer.item[+].answer.valueBoolean = false
* item[=].item[=].answer.item[=].item[=].answer.item[=].linkId = "683622335202"
* item[=].item[=].answer.item[=].item[=].answer.item[=].text = "1. Kontakt erfolgreich?"
* item[=].item[=].answer.item[=].item[=].answer.valueDate = "2025-12-02"
* item[=].item[=].answer.item[=].item[=].linkId = "531811477735"
* item[=].item[=].answer.item[=].item[=].text = "Schriftlicher 1. Versuch (Tag 0 bis 14)"
* item[=].item[=].answer.item[=].item[+].answer.item[0].answer.valueDateTime = "2025-12-03T10:32:43.362Z"
* item[=].item[=].answer.item[=].item[=].answer.item[=].linkId = "354842802717"
* item[=].item[=].answer.item[=].item[=].answer.item[=].text = "ggf. Telefonat 1. Versuch (Tag 35 bis 42)"
* item[=].item[=].answer.item[=].item[=].answer.item[+].answer.valueDateTime = "2025-12-03T13:32:46.881Z"
* item[=].item[=].answer.item[=].item[=].answer.item[=].linkId = "638025827421"
* item[=].item[=].answer.item[=].item[=].answer.item[=].text = "ggf. Telefonat 2. Versuch (Tag 35 bis 42)"
* item[=].item[=].answer.item[=].item[=].answer.item[+].answer.valueDateTime = "2025-12-03T14:32:49.459Z"
* item[=].item[=].answer.item[=].item[=].answer.item[=].linkId = "283707904427"
* item[=].item[=].answer.item[=].item[=].answer.item[=].text = "ggf. Telefonat 3. Versuch (Tag 35 bis 42)"
* item[=].item[=].answer.item[=].item[=].answer.item[+].answer.valueBoolean = false
* item[=].item[=].answer.item[=].item[=].answer.item[=].linkId = "343328919972"
* item[=].item[=].answer.item[=].item[=].answer.item[=].text = "2. Kontakt erfolgreich?"
* item[=].item[=].answer.item[=].item[=].answer.valueDate = "2025-12-03"
* item[=].item[=].answer.item[=].item[=].linkId = "708234487988"
* item[=].item[=].answer.item[=].item[=].text = "Schriftlicher 2. Versuch (Tag 21 bis 35)"
* item[=].item[=].answer.item[=].item[+].answer.item.answer.valueBoolean = false
* item[=].item[=].answer.item[=].item[=].answer.item.linkId = "994511806344"
* item[=].item[=].answer.item[=].item[=].answer.item.text = "3. Kontakt erfolgreich?"
* item[=].item[=].answer.item[=].item[=].answer.valueDate = "2025-12-04"
* item[=].item[=].answer.item[=].item[=].linkId = "120750438814"
* item[=].item[=].answer.item[=].item[=].text = "Schriftlicher 3. Versuch (Tag 42 bis 49)"
* item[=].item[=].answer.item[=].linkId = "653817429944"
* item[=].item[=].answer.item[=].text = "Schriftliches Follow-Up"
* item[=].item[=].answer.item[+].answer[0].item.answer.valueBoolean = false
* item[=].item[=].answer.item[=].answer[=].item.linkId = "242587999496"
* item[=].item[=].answer.item[=].answer[=].item.text = "War die Kontaktaufnahme mit dem Hausarzt erfolgreich?"
* item[=].item[=].answer.item[=].answer[=].valueDateTime = "2025-12-05T10:33:13.988Z"
* item[=].item[=].answer.item[=].answer[+].item.answer.valueBoolean = true
* item[=].item[=].answer.item[=].answer[=].item.linkId = "242587999496"
* item[=].item[=].answer.item[=].answer[=].item.text = "War die Kontaktaufnahme mit dem Hausarzt erfolgreich?"
* item[=].item[=].answer.item[=].answer[=].valueDateTime = "2025-12-05T16:33:21.097Z"
* item[=].item[=].answer.item[=].linkId = "175302299373"
* item[=].item[=].answer.item[=].text = "Kontaktaufnahme Hausarzt (nach Tag 49)"
* item[=].item[=].answer.item[+].answer[0].item.answer.valueBoolean = false
* item[=].item[=].answer.item[=].answer[=].item.linkId = "915186845968"
* item[=].item[=].answer.item[=].answer[=].item.text = "War die Kontaktaufnahme mit dem Einwohnermeldeamt erfolgreich?"
* item[=].item[=].answer.item[=].answer[=].valueDateTime = "2025-12-05T14:33:25.167Z"
* item[=].item[=].answer.item[=].answer[+].item.answer.valueBoolean = true
* item[=].item[=].answer.item[=].answer[=].item.linkId = "915186845968"
* item[=].item[=].answer.item[=].answer[=].item.text = "War die Kontaktaufnahme mit dem Einwohnermeldeamt erfolgreich?"
* item[=].item[=].answer.item[=].answer[=].valueDateTime = "2025-12-05T16:39:31.850Z"
* item[=].item[=].answer.item[=].linkId = "247749186905"
* item[=].item[=].answer.item[=].text = "Kontaktaufnahme Einwohnermeldeamt (nach Tag 49)"
* item[=].item[=].answer.valueCoding = https://www.medizininformatik-initiative.de/fhir/ext/modul-kardio/CodeSystem/mii-cs-kardio-acribis-questionnaire-answer#written_follow_up "Schriftliches Follow-Up (Brief/E-Mail/App, ggf. telefonisch)"
* item[=].item[=].linkId = "243134446838"
* item[=].item[=].text = "In welcher Form erfolgt an Ihrem Standort das Follow-Up?"
* item[=].linkId = "group1"
* item[=].text = "Allgemeine Angaben"
* item[+].item.answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item.answer.item[0].answer.valueDate = "2025-12-04"
* item[=].item.answer.item[=].linkId = "o_2a"
* item[=].item.answer.item[=].text = "Wann ist die Patientin/der Patient verstorben?"
* item[=].item.answer.item[+].answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item.answer.item[=].answer.item.answer.valueCoding = http://snomed.info/sct#22298006 "Myocardial infarction"
* item[=].item.answer.item[=].answer.item.linkId = "o_2c"
* item[=].item.answer.item[=].answer.item.text = "Welche der im Antwortschema aufgeführten Herz-Kreislauf-bedingten Todesursachen lag vor?"
* item[=].item.answer.item[=].linkId = "o_2b"
* item[=].item.answer.item[=].text = "Ist eine Herz-Kreislauf-Erkrankung als Todesursache fesgestellt worden?"
* item[=].item.linkId = "o_2"
* item[=].item.text = "Ist die Patientin/der Patient verstorben?"
* item[=].linkId = "group3"
* item[=].text = "Vitalstatus"
* item[+].item[0].item.answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item[=].item.answer.item.answer[0].valueDate = "2025-12-01"
* item[=].item[=].item.answer.item.answer[+].valueDate = "2025-12-15"
* item[=].item[=].item.answer.item.linkId = "o_3a"
* item[=].item[=].item.answer.item.text = "Wann wurde der Herzinfarkt diagnostiziert?"
* item[=].item[=].item.linkId = "o_3"
* item[=].item[=].item.text = "Wurde ein Herzinfarkt diagnostiziert?"
* item[=].item[=].linkId = "834093031358"
* item[=].item[=].text = "Herzinfarkt"
* item[=].item[+].item.answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item[=].item.answer.item.answer[0].item.answer.valueCoding = http://snomed.info/sct#422504002 "Ischemic stroke"
* item[=].item[=].item.answer.item.answer[=].item.linkId = "o_4b"
* item[=].item[=].item.answer.item.answer[=].item.text = "Wissen Sie welche Art des Schlaganfalls diagnostiziert wurde?"
* item[=].item[=].item.answer.item.answer[=].valueDate = "2025-12-01"
* item[=].item[=].item.answer.item.answer[+].item.answer.valueCoding = http://snomed.info/sct#21454007 "Subarachnoid hemorrhage"
* item[=].item[=].item.answer.item.answer[=].item.linkId = "o_4b"
* item[=].item[=].item.answer.item.answer[=].item.text = "Wissen Sie welche Art des Schlaganfalls diagnostiziert wurde?"
* item[=].item[=].item.answer.item.answer[=].valueDate = "2024-12-11"
* item[=].item[=].item.answer.item.linkId = "o_4a"
* item[=].item[=].item.answer.item.text = "Wann wurde der Schlaganfall / die Erkrankung der Hirngefäße diagnostiziert?"
* item[=].item[=].item.linkId = "o_4"
* item[=].item[=].item.text = "Wurde ein Schlaganfall oder Erkrankung der Hirngefäße diagnostiziert?"
* item[=].item[=].linkId = "650578614260"
* item[=].item[=].text = "Schlaganfall oder Hirnblutung"
* item[=].item[+].item.answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item[=].item.answer.item.answer[0].valueDate = "2025-09-02"
* item[=].item[=].item.answer.item.answer[+].valueDate = "2025-08-05"
* item[=].item[=].item.answer.item.linkId = "o_5a"
* item[=].item[=].item.answer.item.text = "Wann trat(en) diese starke Blutung(en) auf?"
* item[=].item[=].item.linkId = "o_5"
* item[=].item[=].item.text = "Trat eine starke spontane Blutung (Starke Blutung, siehe Infobox) auf, die diagnostiziert wurde und ärztlch behandelt werden musste?"
* item[=].item[=].linkId = "881254946120"
* item[=].item[=].text = "Starke Blutung"
* item[=].item[+].item.answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item[=].item.answer.item.answer[0].valueDate = "2025-07-31"
* item[=].item[=].item.answer.item.answer[+].valueDate = "2025-08-06"
* item[=].item[=].item.answer.item.linkId = "o_6a"
* item[=].item[=].item.answer.item.text = "Wann wurde die Transiente Ischämische Attacke (TIA) diagnostiziert?"
* item[=].item[=].item.linkId = "o_6"
* item[=].item[=].item.text = "Wurde eine Transiente Ischämische Attacke (TIA, siehe Infobox) diagnostiziert?"
* item[=].item[=].linkId = "245973210113"
* item[=].item[=].text = "TIA"
* item[=].item[+].item.answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item[=].item.answer.item.answer[0].valueDate = "2025-12-02"
* item[=].item[=].item.answer.item.answer[+].valueDate = "2025-07-29"
* item[=].item[=].item.answer.item.linkId = "o_7a"
* item[=].item[=].item.answer.item.text = "Wann wurde das Vorhofflimmern diagnostiziert?"
* item[=].item[=].item.linkId = "o_7"
* item[=].item[=].item.text = "Wurde ein Vorhofflimmern (dauerhaft oder anfallsartig) diagnostiziert?"
* item[=].item[=].linkId = "826742623985"
* item[=].item[=].text = "Vorhofflimmern"
* item[=].item[+].item[0].answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item[=].item[=].answer.item.answer[0].valueDate = "2025-07-01"
* item[=].item[=].item[=].answer.item.answer[+].valueDate = "2025-02-12"
* item[=].item[=].item[=].answer.item.linkId = "o_8a"
* item[=].item[=].item[=].answer.item.text = "Wann wurde die Herzinsuffizienz diagnostiziert?"
* item[=].item[=].item[=].linkId = "o_8"
* item[=].item[=].item[=].text = "Wurde eine Herzinsuffizienz (Herzschwäche, siehe Infobox) diagnostiziert?"
* item[=].item[=].item[+].answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item[=].item[=].answer.item[0].answer.valueInteger = 3
* item[=].item[=].item[=].answer.item[=].linkId = "o_9a"
* item[=].item[=].item[=].answer.item[=].text = "Wie häufig war aus diesem Grund im letzten Jahr im Krankenhaus notwendig?"
* item[=].item[=].item[=].answer.item[+].answer[0].valueDate = "2025-12-02"
* item[=].item[=].item[=].answer.item[=].answer[+].valueDate = "2025-08-13"
* item[=].item[=].item[=].answer.item[=].answer[+].valueDate = "2025-05-13"
* item[=].item[=].item[=].answer.item[=].linkId = "o_9b"
* item[=].item[=].item[=].answer.item[=].text = "Wann kam es wegen eine Verschlechterung der Herzinsuffizienz zu einer stationären Aufnahme im Krankenhaus?"
* item[=].item[=].item[=].linkId = "o_9"
* item[=].item[=].item[=].text = "Wurden der Proband/die Probandin aufgrund einer Verschlechterung Ihrer Herzinsuffizienz (siehe Infobox) im letzten Jahr im Krankenhaus behandelt?"
* item[=].item[=].linkId = "944193442011"
* item[=].item[=].text = "Herzinsuffizienz"
* item[=].item[+].item.answer.valueCoding = http://terminology.hl7.org/CodeSystem/v2-0532#Y "Yes"
* item[=].item[=].item.answer.item.answer[0].item.answer.valueDate = "2025-12-02"
* item[=].item[=].item.answer.item.answer[=].item.linkId = "o_10b"
* item[=].item[=].item.answer.item.answer[=].item.text = "Wann wurde diese Erkrankung diagnostiziert?"
* item[=].item[=].item.answer.item.answer[=].valueCoding = http://snomed.info/sct#233916004 "Heart block"
* item[=].item[=].item.answer.item.answer[+].item.answer.valueDate = "2025-06-17"
* item[=].item[=].item.answer.item.answer[=].item.linkId = "o_10b"
* item[=].item[=].item.answer.item.answer[=].item.text = "Wann wurde diese Erkrankung diagnostiziert?"
* item[=].item[=].item.answer.item.answer[=].valueCoding = http://snomed.info/sct#307409006 "Ischemic finger"
* item[=].item[=].item.answer.item.linkId = "o_10a"
* item[=].item[=].item.answer.item.text = "Um welche weitere Herz-Kreislauf-Erkrankung handelt es sich?"
* item[=].item[=].item.linkId = "o_10"
* item[=].item[=].item.text = "Wurden weitere Herz-Kreislauf-Erkrankungen diagnostiziert?"
* item[=].item[=].linkId = "442060932628"
* item[=].item[=].text = "Weitere Herz-Kreislauf-Erkrankung"
* item[=].linkId = "group4"
* item[=].text = "Diagnosen im letzten Jahr (seit Teilnahme an der Acribis-Studie)"
* item[+].item.answer.valueCoding = http://terminology.hl7.org/CodeSystem/v3-ParticipationMode#ONLINEWRIT "online written"
* item[=].item.linkId = "o_11"
* item[=].item.text = "Wie wurde das Follow-Up erhoben?"
* item[=].linkId = "101636668393"
* item[=].text = "Allgemeine Angaben 2"
* language = #de
* status = #completed
* subject = Reference(Beispielpatient)
* authored = "2025-11-20T14:07:36.673Z"
* questionnaire = "https://www.medizininformatik-initiative.de/fhir/ext/modul-kardio/Questionnaire/mii-qn-kardio-acribis-study-followup"