// ============================================================================
// Pathologie Bundle
// ============================================================================

Instance: mii-exa-test-data-bundle-patho-1
InstanceOf: Bundle
Usage: #example
Description: "Bundle: Pathologie Testdaten Patient-1"
* insert TestDataLabel
* meta.source = "https://www.charite.de/fhir/kds-testdata"
* type = #transaction
* timestamp = "2025-06-18T13:51:00+02:00"
* insert AddBundleEntry(mii-exa-test-data-patho-patient-1, Patient)
* insert AddBundleEntry(mii-exa-test-data-patho-encounter-1, Encounter)
// Pathologie Resources
* insert AddBundleEntry(mii-exa-test-data-patient-1-patho-active-problems-1, List)
* insert AddBundleEntry(mii-exa-test-data-patient-1-patho-hopi-1, List)
* insert AddBundleEntry(mii-exa-test-data-patient-1-patho-problem-list-item-1, Condition)
* insert AddBundleEntry(mii-exa-test-data-patho-composition-1, Composition)
* insert AddBundleEntry(mii-exa-test-data-patho-diagnose-gesichert-1, Condition)
* insert AddBundleEntry(mii-exa-test-data-patho-diagnose-verdacht-1, Condition)
* insert AddBundleEntry(mii-exa-test-data-patho-report-1, DiagnosticReport)
* insert AddBundleEntry(mii-exa-test-data-patho-image-1, Media)
* insert AddBundleEntry(mii-exa-test-data-patho-image-2, Media)
* insert AddBundleEntry(mii-exa-test-data-patho-asap, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-conclusion-grouper-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-gleason-grading-01, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-gleason-score-total, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-grading-group-isup, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-granulomatous-prostatitis, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-high-grade-pin, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-histo-typ-01, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-histo-typ-03, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-histological-grade-who, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-histological-type-icdo-3, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-icdo-version, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-intraductal-carcinoma, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-intraop-befund-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-intraop-grouper-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-lymphovascular-invasion, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-macro-grouper-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-macroscopic-cylinder-count-01, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-macroscopic-cylinder-count-03, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-macroscopic-laterality-01, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-macroscopic-laterality-03, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-macroscopic-length-01, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-macroscopic-length-03, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-micro-grouper-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-morph-text-01, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-morph-text-03, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-morphology-free-text, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-p63-befund-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-percentage-gleason-45, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-percentage-tumor-total, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-perineural-infiltration, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-periprostatatic-fat-invasion, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-positive-cores-left, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-positive-cores-right, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-primaer-gleason-01, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-primary-gleason-pattern, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-psa-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-ratio-positive-cores, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-secondary-gleason-pattern, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-sekundaer-gleason-01, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-seminal-vesicle-invasion, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-tnm-m-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-tnm-n-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-tnm-t-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-tumor-length-total, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-tumoranteil-01, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-zusatz-grouper-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-organization-1, Organization)
* insert AddBundleEntry(mii-exa-test-data-patho-practitioner-1, Practitioner)
* insert AddBundleEntry(mii-exa-test-data-patho-practitioner-2, Practitioner)
* insert AddBundleEntry(mii-exa-test-data-patho-request-1, ServiceRequest)
* insert AddBundleEntry(mii-exa-test-data-patho-specimen-01-block, Specimen)
* insert AddBundleEntry(mii-exa-test-data-patho-imaging-study-1, ImagingStudy)
* insert AddBundleEntry(mii-exa-test-data-patho-body-structure-1, BodyStructure)
* insert AddBundleEntry(mii-exa-test-data-patho-substance-formalin-1, Substance)
* insert AddBundleEntry(mii-exa-test-data-patho-composition-0, Composition)
* insert AddBundleEntry(mii-exa-test-data-patho-specimen-01-part, Specimen)
* insert AddBundleEntry(mii-exa-test-data-patho-specimen-01-slide, Specimen)
* insert AddBundleEntry(mii-exa-test-data-patho-specimen-03-block, Specimen)
* insert AddBundleEntry(mii-exa-test-data-patho-specimen-03-part, Specimen)
* insert AddBundleEntry(mii-exa-test-data-patho-specimen-03-slide, Specimen)
// Grouper-Varianten mit component.dataAbsentReason (MS-Coverage)
* insert AddBundleEntry(mii-exa-test-data-patho-macro-grouper-dar-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-micro-grouper-dar-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-intraop-grouper-dar-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-conclusion-grouper-dar-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-zusatz-grouper-dar-1, Observation)
* insert AddBundleEntry(mii-exa-test-data-patho-befund-bundle-1, Bundle)
