// ============================================================================
// MII Patho Test Data - Befunddokument-Bundle (mii-pr-patho-bundle)
// Dokument-Bundle nach ISiKBerichtBundle: Composition als erster Entry,
// alle Ressourcen der Befundkette als weitere Entries.
// Hinweis: Das Patho-Modul 2027.0.0-ballot liefert selbst KEIN Bundle-Beispiel;
// dies ist die erste vollstaendig verkettete Bundle-Instanz.
// TNM-Observations und die gesicherte Diagnose sind bewusst NICHT Teil des
// Dokuments (von keiner Dokument-Ressource referenziert); sie stehen nur im
// Transaction-Bundle mii-exa-test-data-bundle-patho-1.
// ============================================================================

RuleSet: PathoDocEntrySliced(resource, type, slice)
* entry[{slice}][+].fullUrl = "https://www.medizininformatik-initiative.de/{type}/{resource}"
* entry[{slice}][=].resource = {resource}

RuleSet: PathoDocEntryPlain(resource, type)
* entry[+].fullUrl = "https://www.medizininformatik-initiative.de/{type}/{resource}"
* entry[=].resource = {resource}

Instance: mii-exa-test-data-patho-befund-bundle-1
InstanceOf: https://www.medizininformatik-initiative.de/fhir/ext/modul-patho/StructureDefinition/mii-pr-patho-bundle
Usage: #example
Title: "Befunddokument Prostatabiopsie"
Description: "Dokument-Bundle: vollstaendiger Prostatabiopsie-Befundbericht (12 Stanzen) nach mii-pr-patho-bundle"
* insert TestDataLabel
* meta.source = "https://www.charite.de/fhir/kds-testdata"
* identifier.system = "https://www.charite.de/fhir/sid/patho/befundbericht"
* identifier.value = "E_24_001-DOC"
* type = #document
* timestamp = "2024-01-20T15:30:00+01:00"
* signature.type = urn:iso-astm:E1762-95:2013#1.2.840.10065.1.12.1.1 "Author's Signature"
* signature.when = "2024-01-20T15:30:00+01:00"
* signature.who = Reference(mii-exa-test-data-patho-organization-1)

// Entry 0: Composition (muss erster Entry sein)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-composition-1, Composition, Composition)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-patient-1, Patient, Patient)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-encounter-1, Encounter, Encounter)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-request-1, ServiceRequest, ServiceRequest)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-01-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-01-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-01-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-02-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-02-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-02-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-03-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-03-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-03-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-04-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-04-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-04-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-05-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-05-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-05-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-06-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-06-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-06-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-07-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-07-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-07-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-08-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-08-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-08-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-09-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-09-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-09-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-10-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-10-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-10-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-11-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-11-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-11-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-12-block, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-12-part, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-specimen-12-slide, Specimen, Specimen)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-report-1, DiagnosticReport, DiagnosticReport)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-asap, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-asap-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-asap-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-asap-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-asap-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-asap-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-asap-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-asap-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-conclusion-grouper-1, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-extraprostatic-extension-location, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-gleason-grading-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-gleason-grading-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-gleason-grading-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-gleason-grading-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-gleason-grading-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-gleason-grading-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-gleason-grading-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-gleason-score-total, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-grading-group-isup, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-granulomatoese-prostatitis-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-granulomatoese-prostatitis-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-granulomatoese-prostatitis-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-granulomatoese-prostatitis-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-granulomatoese-prostatitis-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-granulomatoese-prostatitis-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-granulomatoese-prostatitis-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-granulomatous-prostatitis, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-high-grade-pin, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-high-grade-pin-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-high-grade-pin-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-high-grade-pin-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-high-grade-pin-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-high-grade-pin-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-high-grade-pin-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-high-grade-pin-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-03, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-05, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-08, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-10, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histo-typ-12, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histological-grade-who, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-histological-type-icdo-3, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-icdo-version, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraductal-carcinoma, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraduktales-karzinom-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraduktales-karzinom-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraduktales-karzinom-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraduktales-karzinom-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraduktales-karzinom-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraduktales-karzinom-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraduktales-karzinom-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraop-befund-1, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-intraop-grouper-1, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-lymphovascular-invasion, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-lymphovaskulaere-invasion-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-lymphovaskulaere-invasion-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-lymphovaskulaere-invasion-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-lymphovaskulaere-invasion-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-lymphovaskulaere-invasion-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-lymphovaskulaere-invasion-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-lymphovaskulaere-invasion-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macro-grouper-1, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-03, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-05, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-08, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-10, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-cylinder-count-12, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-03, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-05, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-08, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-10, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-laterality-12, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-03, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-05, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-08, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-10, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-macroscopic-length-12, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-micro-grouper-1, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-03, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-05, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-08, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-10, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morph-text-12, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-morphology-free-text, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-p63-befund-1, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-percentage-gleason-45, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-percentage-tumor-total, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-perineural-infiltration, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-perineurale-infiltration-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-perineurale-infiltration-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-perineurale-infiltration-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-perineurale-infiltration-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-perineurale-infiltration-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-perineurale-infiltration-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-perineurale-infiltration-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-periprostatatic-fat-invasion, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-positive-cores-left, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-positive-cores-right, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-primaer-gleason-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-primaer-gleason-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-primaer-gleason-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-primaer-gleason-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-primaer-gleason-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-primaer-gleason-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-primaer-gleason-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-primary-gleason-pattern, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-prozent-gleason-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-prozent-gleason-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-prozent-gleason-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-prozent-gleason-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-prozent-gleason-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-prozent-gleason-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-prozent-gleason-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-psa-1, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-ratio-positive-cores, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-secondary-gleason-pattern, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-sekundaer-gleason-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-sekundaer-gleason-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-sekundaer-gleason-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-sekundaer-gleason-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-sekundaer-gleason-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-sekundaer-gleason-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-sekundaer-gleason-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-seminal-vesicle-invasion, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumor-length-total, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumoranteil-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumoranteil-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumoranteil-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumoranteil-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumoranteil-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumoranteil-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumoranteil-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumorbefallin-laenge-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumorbefallin-laenge-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumorbefallin-laenge-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumorbefallin-laenge-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumorbefallin-laenge-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumorbefallin-laenge-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumorbefallin-laenge-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweis-in-fettgewebe-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweis-in-fettgewebe-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweis-in-fettgewebe-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweis-in-fettgewebe-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweis-in-fettgewebe-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweis-in-fettgewebe-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweis-in-fettgewebe-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweisin-samenblase-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweisin-samenblase-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweisin-samenblase-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweisin-samenblase-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweisin-samenblase-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweisin-samenblase-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-tumornachweisin-samenblase-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-verhaeltnis-positiver-stanzen-01, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-verhaeltnis-positiver-stanzen-02, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-verhaeltnis-positiver-stanzen-04, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-verhaeltnis-positiver-stanzen-06, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-verhaeltnis-positiver-stanzen-07, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-verhaeltnis-positiver-stanzen-09, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-verhaeltnis-positiver-stanzen-11, Observation, Observations)
* insert PathoDocEntrySliced(mii-exa-test-data-patho-zusatz-grouper-1, Observation, Observations)
* insert PathoDocEntryPlain(mii-exa-test-data-patho-diagnose-verdacht-1, Condition)
* insert PathoDocEntryPlain(mii-exa-test-data-patho-image-1, Media)
* insert PathoDocEntryPlain(mii-exa-test-data-patho-organization-1, Organization)
* insert PathoDocEntryPlain(mii-exa-test-data-patho-practitioner-1, Practitioner)
* insert PathoDocEntryPlain(mii-exa-test-data-patho-practitioner-2, Practitioner)
* insert PathoDocEntryPlain(mii-exa-test-data-patient-1-patho-active-problems-1, List)
* insert PathoDocEntryPlain(mii-exa-test-data-patient-1-patho-hopi-1, List)
* insert PathoDocEntryPlain(mii-exa-test-data-patient-1-patho-problem-list-item-1, Condition)
